### ISSUE TITLE
Questions on how to use it

### ISSUE THREAD

**Issue by Wandaboma** [udayRage/PAMI#10]
Hello, I am a researcher that recently encountered a problem which requires me to use sequence pattern mining algorithm, so I found this package which is perfect. However, I still have some issues using it because there is too little information and documentation on this project, I don't know how to do the visualization and how to switch algorithms. It would be great if there is more manual, tutorial, etc.

**Comment by udayRage** [comment]
Dear Wandaboma,

Good day!

                We will prepare the necessary manual and let you know. We will update you once the manuals were completed. 

Regards
Uday

**Comment by Wandaboma** [comment]
Thanks! Then I will be waiting for more updates.

**Comment by udayRage** [comment]
Dear Wandaboma,

    We have prepared manuals for using our algorithms. Please check them out.
