### ISSUE TITLE
Add #frequent-pattern-mining to the Repo

### ISSUE THREAD

**Issue by BieniekAlexander** [udayRage/PAMI#23]
I'm looking at various repos for the purpose of frequent pattern mining. I found this repo in [this article](https://towardsdatascience.com/hello-i-am-pami-937439c7984d), and I think the repo can be added to [this topic](https://github.com/topics/frequent-pattern-mining?l=python) for more visibility.

**Comment by udayRage** [comment]
Dear Alexandar,

Good day!

         I'm sorry for not getting back to you sooner. 

        Thank you very much for your valuable input. We have now added #frequent-pattern-mining to our repository.

        Please continue providing your valuable feedback in the future.

Regards
Uday
