### ISSUE TITLE
Error on converting a sparse dataframe into a transactional database

### ISSUE THREAD

**Issue by catarinarurbano** [udayRage/PAMI#5]
When trying to convert a sparse dataframe into a transactional database, through the code provided on [link](https://github.com/udayRage/PAMI/blob/main/docs/sparseDF2DB.md) the following error appears :  " AttributeError: module 'PAMI.extras.DF2DB.sparseDF2DB' has no attribute 'sparse2DB'. "

Firstly, I simply change the word sparse2DB to sparseDF2DB, but then a different error appears " ValueError: DataFrame constructor not properly called! " 
My dataframe was already imported into the Jupyter notebook when I called it to the function, however, I also tried to save it and export it as an excel file and import it directly on the function, however, nothing worked and the error persisted.

Can you please help?

Thanks in advance.

**Comment by udayRage** [comment]
Thank you very much for reporting the issue. It seems the error is due to a change in the function name, which was not reflected in the manual. We will modify the manual to reflect the recent latest changes made in the code.

We will update this post, with the result in two days.

**Comment by udayRage** [comment]
We have resolved the error by updating the manual. 
We request you to check the manual and perform your analytics.

Once again, thank you very much for raising the issues.
